### ISSUE TITLE
No successful run when using this action (firebase-cli incompatible with the version of nodejs)

### ISSUE THREAD

**Issue by drewisdorner** [vudodov/deploy-hugo-to-the-firebase#1]
Hello,
I'd try using this action and ran into the following error:

```
Run vudodov/deploy-hugo-to-the-firebase@v0.3
[4](https://github.com/***/***/runs/6609806508?check_suite_focus=true#step:4:5)
/usr/bin/docker run --name d17d92aa0736947ffbc328ea987043d93_f2f405 --label 08450d --workdir /github/workspace --rm -e INPUT_FIREBASE-TOKEN -e INPUT_ALIAS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/******":"/github/workspace" 08450d:17d92aa0736947ffbc328ea987043d93  "***" ""

Firebase CLI v11.0.1 is incompatible with Node.js v12.18.0 Please upgrade Node.js to version >= 14.18.0
```

I'm using the following workflow configuration:

```YAML
name: Deploy Hugo to Firebase
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Deploy Hugo to Firebase
      uses: vudodov/deploy-hugo-to-the-firebase@v0.3
      with:
        firebase-token: ${{ secrets.firebase_token }}
```

I've also tried it with `@master` and had the same error appear.

Is there anything you suggest to get this issue resolved?
